package.json, src/commands/miscellaneous/reminder.js
I didn't test it yet so I may either made new bugs or just shorted the code
=> Shorted the reminder command removing the switch

src/commands/Miscellaneous/jumbo.js, src/commands/Moderation/multiban.js, src/commands/Moderation/multikick.js, src/commands/Moderation/multiunban.js, src/commands/Moderation/multivoicekick.js, src/commands/Moderation/multiwarn.js, src/utils/AutoMod.js, src/utils/Regex.js
Should work as expected/intended now
=> Fix regular expressions matching wrong things

src/languages/cs-CZ.json
I did mostly fixed typos like missing letters, letters in wrong position etc.
=> Fixing typos in Czech language

src/languages/cs-CZ.json
I did fixed some typos also on line 37,38 I did add "Režim" after word NSFW which could be more clear than original sentence.
=> Czech language typos fixing

src/commands/Miscellaneous/jumbo.js
This is with minimal modification to existing code. With some changes, this can be made shorter and a bit more efficient.
=> Correction for emoji fe0f issue

src/events/message.js, src/utils/AutoMod.js, src/utils/clearance/user/UserClearance.js
Also simplified message event a little bit. There's a lot of red in the combined diff, but most of it is just whitespace changes being represented weirdly.
=> Fix bot ping as prefix for commands with arguments

src/index.ts, src/languages/sk-SK.json, src/utils/BulbBotUtils.ts
=> Full Slovak Translation

src/structures/CommandContext.ts
Should fix the cause of the DM construction crash which was resolved in 827289c. If we ever decide to do interactions in DMs, we'll want this problem to be gone already
=> Fix invalid channel assignment

.github/CODEOWNERS, interactionCommands.json, src/commands/Configuration/configure.ts, src/commands/Configuration/configure/rolesOnLeave.ts, src/commands/Configuration/settings.ts, src/events/guild/member/guildMemberRemove.ts, src/languages/en-US.json, src/utils/database/models/GuildConfiguration.ts, src/utils/managers/DatabaseManager.ts
- Adds configurable feature to log the roles of members when the leave the server as part of the leave-log
- Adds config command `roles_on_leave` to enable/disable the feature above
- Adds slash command for `roles_on_leave` config command
- **This pull request adds/removes columns to/from a DB model and will require a DB sync**
=> Role logging when members leave

src/Config.ts
Probably solves #186 but this needs to be confirmed
=> Add voice state intent

src/structures/Util.ts, src/utils/BulbBotUtils.ts
We'll at least know which event now. This should help address the really cryptic stack traces we get
=> Improve error logging when thrown in an event

src/commands/Moderation/multiwarn.ts, src/commands/Moderation/warn.ts, src/interactions/context/warn.ts, src/structures/CommandContext.ts, src/utils/AutoMod.ts, src/utils/managers/AutoModManager.ts, src/utils/managers/InfractionsManager.ts
=> Automod bugfixes

src/structures/CommandContext.ts, src/structures/Util.ts, src/utils/AutoMod.ts
Mostly aimed at bugs that pop up in our internal error logs. Not sure how high the user impact is, but this will at least help thin the log out so we can see real bugs more easily.
Resolves #230 
Resolves #231 
Resolves #233
=> Fix log bugs

src/commands/Miscellaneous/permissions.ts, src/languages/en-US.json
Deconstructs permissions integers
=> Permissions command

src/commands/Configuration/configure/muterole.ts, src/events/guild/channels/channelCreate.ts, src/utils/BulbBotUtils.ts
Made the bot automatically overwrite all channels with the mute role when initially setting up the role and when creating new channels
=> Automatic muterole setup

src/commands/Moderation/mute.ts, src/commands/Moderation/unmute.ts, src/events/message/messageCreate.ts, src/interactions/context/mute.ts, src/languages/en-US.json, src/utils/Restoration.ts, src/utils/managers/InfractionsManager.ts
Unless https://github.com/discordjs/discord.js/pull/6949 merges before the feature is globally launched we have working feature right now. 
Feel free to check it rn now tho.
Could maybe put it in some testing bucket or something idk, thoughts for another day
=> update(Mute) adds the new timeout feature to the bot

src/events/guild/member/guildMemberUpdate.ts, src/utils/BulbBotUtils.ts, src/utils/managers/DatabaseManager.ts
- delete data on removal
- null check
- check permssions
=> bug: fixed 3 internal bugs

src/commands/Moderation/kick.ts, src/commands/Moderation/undeafen.ts
Fixes a bug where kick log messages would not display the user tag correctly
=> Fix strings formatting

src/commands/Moderation/multiban.ts, src/commands/Moderation/multikick.ts, src/commands/Moderation/multiunban.ts, src/commands/Moderation/multiwarn.ts
This PR:
- Removes the extra space before the user list in multi commands confirmation messages
- Adds commas between users in said list
- Fixes the issue #185
=> Multi commands fixes

src/events/message/messageUpdate.ts
=> Probably fix that null author error we've been seeing

src/events/guild/roles/roleUpdate.ts
- Remove `@ts-nocheck` annotation. I don't remember why it was there, but whatever the reason, it would've been intended to have been removed a long time ago and was forgotten
- Pass correct parameters to function calls
- Fix type errors
Resolves #389
=> Fix roleUpdate

src/events/message/messageDelete.ts, src/utils/BulbBotFetch.ts
- Create bulbfetch generalization
- Fix messageDelete type errors
=> Refactor bulbfetch & fix messageDelete errors

src/commands/Miscellaneous/remind/set.ts, src/utils/Restoration.ts
- pings when it restores bugs
- shouldnt reply to messages with no message id
=> bug: fixed reminder bugs
